#!/bin/sh

# By Guillaume Ponçon

perl-rename 's/ç/c/gi' *
perl-rename 's/é/e/gi' *
perl-rename 's/è/e/gi' *
perl-rename 's/ê/e/gi' *
perl-rename 's/à/a/gi' *
perl-rename 's/@/a/gi' *
perl-rename 's/ù/u/gi' *
perl-rename 's/î/i/gi' *
perl-rename 's/€/e/gi' *
perl-rename 's/^[^0-9a-zA-Z_.]+//' *
perl-rename 's/[^0-9a-zA-Z_.]/-/g' *
perl-rename 's/-+/-/g' *
perl-rename 's/_+/_/g' *
perl-rename 's/[_-][_-]+/-/g' *
perl-rename 's/[\.-][\.-]+/./g' *
perl-rename 'y/A-Z/a-z/' *
perl-rename 's/[\._-]+$//' *