#!/bin/sh

# By Guillaume Ponçon

rename 's/ç/c/gi' *
rename 's/é/e/gi' *
rename 's/è/e/gi' *
rename 's/ê/e/gi' *
rename 's/à/a/gi' *
rename 's/@/a/gi' *
rename 's/ù/u/gi' *
rename 's/î/i/gi' *
rename 's/€/e/gi' *
rename 's/^[^0-9a-zA-Z_.]+//' *
rename 's/[^0-9a-zA-Z_.]/-/g' *
rename 's/-+/-/g' *
rename 's/_+/_/g' *
rename 's/[_-][_-]+/-/g' *
rename 's/[\.-][\.-]+/./g' *
rename 'y/A-Z/a-z/' *
rename 's/[\._-]+$//' *